### ISSUE TITLE
Using validate binding behaviour but not calling ValidationEngine.getValidationReporter(this) causes the view to fail

### ISSUE THREAD

**Issue by apawsey** [aurelia/validatejs#37] opened 2016-05-08 19:55 UTC
If you configure validation rules, and use the validate binding behaviour in you markup, but you do not call the getValidationReporter method, you get the following error...

```
ERROR [app-router] TypeError: Cannot read property 'subscribe' of undefined
    at ValidateBindingBehavior.bind (webpack:///./~/aurelia-validatejs/dist/commonjs/validate-binding-behavior.js?:31:13)
    at BindingBehavior.bind (webpack:///./~/aurelia-binding/dist/commonjs/aurelia-binding.js?:1195:19)
    at Binding.bind (webpack:///./~/aurelia-binding/dist/commonjs/aurelia-binding.js?:4672:29)
......
```

Surely this should be automatically called if it doesn't already exist as it seems to be some kind of singleton for each model?

**Comment by PWKad** [comment] 2016-05-09 22:43
Duplicate of #25

**Closed by PWKad** 2016-05-09 22:43 UTC
