### ISSUE TITLE
Validation Decorator - Property Rewrite

### ISSUE THREAD

**Issue by ppn2** [aurelia/validatejs#55] opened 2016-05-15 04:05 UTC
Can we please avoid property rewrite. I don't think it is good idea to touch the model objects in general. In our case, in some of the properties we have getter and setters and aurelia is breaking them when validation decorator is defined on them.

**Comment by EisenbergEffect** [comment] 2016-05-15 12:51
@PWKad Didn't we recently discuss removing the property re-writing in favor of leeting that all be handled by the validate binding behavior?

**Comment by PWKad** [comment] 2016-05-17 01:55
Duplicate of https://github.com/aurelia/validatejs/issues/21

**Closed by PWKad** 2016-05-17 01:55 UTC
